---
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test

syntax:
  stage: test
  image: php:8
  before_script:
    - apt-get update
    - apt-get -y install wget unzip
    - wget https://getcomposer.org/download/latest-stable/composer.phar
    - chmod +x composer.phar
    - mv composer.phar /usr/bin/composer
    - pecl install xdebug
    - docker-php-ext-install zip
    - docker-php-ext-enable xdebug zip
    - composer install
  script: 
    - composer syntax

phpunit:
  stage: test
  image: php:8
  before_script:
    - apt-get update
    - apt-get -y install wget unzip
    - wget https://getcomposer.org/download/latest-stable/composer.phar
    - chmod +x composer.phar
    - mv composer.phar /usr/bin/composer
    - pecl install xdebug
    - docker-php-ext-install zip
    - docker-php-ext-enable xdebug zip
    - composer install
  script: 
    - composer phpunit
