language: php

matrix:
  include:
    - php: 8.0
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - composer phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
