language: php

env:
  global:
    - XDEBUG_MODE=coverage

matrix:
  include:
    - php: 8.0
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer install
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer phpunit

after_success:
  - ./cc-test-reporter after-build -t clover --exit-code $TRAVIS_TEST_RESULT